api:
  id: "19593586"
platform:
  client_id: "![uavU1RDB0/7IyBKQPSQ5+LbY0IyohqlhB9TPhLqh8AbcqHKLIubryw==]"
  client_secret: "![e1wNr0JBrjBqh59yjACbWKzTMFVOELpGqexe24qryHKnqrqaE59bxQ==]"

salesforce:
  username: "![foKQrVSLEOjELQMJQyBlyhLg4YeStOrC7s3ShEPVyhc=]"
  password: "![LBlKW5jyrFChQdxwstwzrw==]"
  token: "![5bZKLspbo6bFbcO1Z61cDKQc+Sd2Od+35BNwQohijFk=]"